spring:
  config:
    activate:
      on-profile: dev
    import: secret.properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DEV_DB_ENDPOINT}:3306/${DEV_DB_NAME}?serverTimezone=KST
    username: ${DEV_DB_USER}
    password: ${DEV_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: ${JWT_SECRET}

sentry:
  dsn: ${SENTRY_DSN}
  environment: local
  traces-sample-rate: 1.0
  enable-tracing: true
  exception-resolver-order: -2147483647

slack:
  bot:
    token: ${SLACK_BOT_TOKEN}
  channel:
    sign-in: ${SLACK_SIGNIN_CHANNEL}
    monitor: ${SLACK_MONITORING_CHANNEL}

fcm:
  file-path: pophory_fcm.json
  api:
    url: ${FCM_URL}
  google:
    api: https://www.googleapis.com/auth/cloud-platform

cloud:
  aws:
    CLOUDFRONT: ${CLOUDFRONT}
    region:
      static: ${S3_REGION}
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET}
pophorysm:
  id: ${POPHORYSM_ID}

springdoc:
  packages-to-scan: com.pophory.pophoryapi
  api-docs:
    enabled: true
  use-fqn: true