name: Pophory CI

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: application.yml
        run: |
          ## create application.yml
          cd ./pophory-api/src/main/resources
          
          # application.yml 파일 생성
          touch ./application.yml
          touch ./application-infra.yml
          touch ./pophory_fcm.json
          
          # GitHub-Actions 에서 설정한 값을 application.yml 파일에 쓰기
          echo "${{ secrets.APPLICATION }}" >> ./application.yml
          echo "${{ secrets.APPLICATION_INFRA }}" >> ./application-infra.yml
          echo "${{ secrets.FCM_JSON }}" >> ./popory_fcm.json
          
          
          # application.yml 파일 확인
          cat ./application.yml
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test
